version: "{build}"
skip_tags: false

platform: x64
configuration: Release

clone_folder: C:\infoware

build_script:
  - git submodule update --init --recursive
  - md build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DINFOWARE_EXAMPLES=ON -DINFOWARE_TESTS=ON -DINFOWARE_USE_D3D=ON ..
  - cmake --build . --config Release

test_script:
  - ctest --output-on-failure --build-config Release

notifications:
  - provider: Email
    to:
      - nabijaczleweli@gmail.com
      - phdofthehouse@gmail.com
    on_build_status_changed: true
